ALTER TABLE public.work_entries
  ADD COLUMN entry_number INTEGER GENERATED BY DEFAULT AS IDENTITY;

WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at ASC) AS rn
  FROM public.work_entries
  WHERE entry_number IS NULL
)
UPDATE public.work_entries we
SET entry_number = ordered.rn
FROM ordered
WHERE we.id = ordered.id;

SELECT setval(
  pg_get_serial_sequence('public.work_entries', 'entry_number'),
  (SELECT MAX(entry_number) FROM public.work_entries),
  true
);

ALTER TABLE public.work_entries
  ALTER COLUMN entry_number SET NOT NULL;

ALTER TABLE public.work_entries
  ADD CONSTRAINT work_entries_entry_number_key UNIQUE (entry_number);

ALTER TABLE public.work_entries
  ADD COLUMN entry_code TEXT
    GENERATED ALWAYS AS ('VME-' || entry_number::text) STORED;
